In [19]:
N=input()
a=[i*int(N) for i in range(1,11)]
print(a)
for i in range(1,11):
    print(f'{i} * {N} = {i*int(N)}')

5
[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]
1 * 5 = 5
2 * 5 = 10
3 * 5 = 15
4 * 5 = 20
5 * 5 = 25
6 * 5 = 30
7 * 5 = 35
8 * 5 = 40
9 * 5 = 45
10 * 5 = 50


In [22]:
N=input()
a=1
for i in range(int(N),0,-1):
    a*=i
print(a)

1
1


In [21]:
lst=['car','train','flight','bike']
list.sort(lst,key=len)
lst

['car', 'bike', 'train', 'flight']

In [23]:
import numpy as np

In [24]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [25]:
arr=np.array([[1,2,3,4,5],[1,2,3,4,5]])
arr

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [26]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)


In [32]:
x.ndim

2

In [27]:
type(x)
#<class 'numpy.ndarray'>

numpy.ndarray

In [28]:
x.shape
#(2, 3)


(2, 3)

In [29]:
x.dtype
#dtype('int32')

dtype('int32')

In [33]:
x.size


6

In [34]:
x[1, 2]

6

In [35]:
y = x[:,1]
y


array([2, 5])

In [36]:
y[0] = 9 # this also changes the corresponding element in x

y

array([9, 5])

In [37]:
x

array([[1, 9, 3],
       [4, 5, 6]])

In [38]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [39]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [40]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [42]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [47]:
arr=np.random.randint(1,10,10)
arr

array([9, 9, 9, 3, 7, 3, 5, 7, 2, 2])

In [48]:
arr[:5]

array([9, 9, 9, 3, 7])

In [49]:
arr[-5:]

array([3, 5, 7, 2, 2])

In [50]:
arr[3]

3

In [52]:
arr[3:4]

array([3])

In [53]:
type(arr[3:4])

numpy.ndarray

In [55]:
if arr[3]==3:
    print('yes')

yes


In [54]:
if arr[3:4]==3:
    print('yes')

yes


In [56]:
if arr[1:2]==3:
    print('yes')
else:
    print('no')

no


In [57]:
arr[1:2]==3

array([False])

In [60]:
arr[3:5]==3

array([ True, False])

In [62]:
marks=np.array([65,55,45,78])

if np.all(marks>35):
    print('All Passed')
else:
    print('Fail')

All Passed


In [63]:
new_arr=arr[[5,3,2]] #arr=array([9, 9, 9, 3, 7, 3, 5, 7, 2, 2])
new_arr 

array([3, 3, 9])

In [65]:
arr[arr>5]

array([9, 9, 9, 7, 7])

In [73]:
arr[arr > np.max(arr)/2]

array([9, 9, 9, 7, 5, 7])